# Generated by Django 4.2 on 2023-04-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=123)),
                ('lname', models.CharField(default='', max_length=123)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default='', max_length=12)),
                ('text', models.TextField()),
            ],
        ),
    ]
